name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure OS
      run: sudo apt-get update -y -qq

    - name: Check GCC
      run: g++ --version

    - name: Configure SDL
      run: sudo apt-get -y install libsdl2-dev

    - name: Configure Vulkan
      run: sudo apt-get -y install libvulkan-dev

    - name: Configure Shaderc
      run: |
         git clone https://github.com/google/shaderc.git;
         cd ./shaderc;
         ./utils/git-sync-deps;
         cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}};
         cd build
         sudo make install -j4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
