name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update OS
      run: sudo apt-get update -y -qq

    - name: Add Dependancy- SDL
      run: sudo apt-get -y install libsdl2-dev

    - name: Add Dependancy- Vulkan
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.198-focal.list https://packages.lunarg.com/vulkan/1.2.198/lunarg-vulkan-1.2.198-focal.list
        sudo apt update
        sudo apt install vulkan-sdk
    
    - name: Add Dependancy- googletest
      run: |
        git clone https://github.com/google/googletest.git
        cd ./googletest
        cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}};
        cd build
        sudo make install -j8
        
    - name: Add Dependancy- shaderc
      run: |
         git clone https://github.com/google/shaderc.git;
         cd ./shaderc;
         ./utils/git-sync-deps;
         cmake -B ./build -DBUILD_GMOCK=OFF -DBUILD_EXTERNAL=OFF -DENABLE_CTEST=OFF -DEFFCEE_BUILD_SAMPLES=OFF -DEFFCEE_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}};
         cd build
         sudo make install -j8

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
